import type { Company } from "@crm/types";
import { generateUUID, now } from "@crm/utils";
import { companyQueries } from "./queries/companies";
import { sql as db } from "./client";

function pastDate(daysAgo: number): string {
  return new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000).toISOString();
}

// ============================================
// 25 Serbian Companies - Real Data
// ============================================

export const SERBIAN_COMPANIES: Company[] = [
  {
    id: generateUUID(),
    name: "NIS a.d. Novi Sad",
    industry: "Energy",
    address: "Narodnog fronta 12",
    email: "info@nis.rs",
    phone: "+381 21 481 1111",
    website: "www.nis.rs",
    contact: "Marko Petrović",
    vatNumber: "104052135",
    companyNumber: "20084693",
    city: "Novi Sad",
    country: "Serbia",
    countryCode: "RS",
    zip: "21000",
    note: "Najveća energetska kompanija u Srbiji, bavi se naftom i gasom.",
    createdAt: pastDate(365),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Telekom Srbija a.d.",
    industry: "Telecommunications",
    address: "Takovska 2",
    email: "info@telekom.rs",
    phone: "+381 11 331 0000",
    website: "www.telekom.rs",
    contact: "Vladimir Lučić",
    vatNumber: "100002887",
    companyNumber: "17162543",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11000",
    note: "Vodeći telekomunikacioni operator u Srbiji.",
    createdAt: pastDate(400),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Delhaize Serbia d.o.o.",
    industry: "Retail",
    address: "Jurija Gagarina 14",
    email: "info@maxi.rs",
    phone: "+381 11 209 5555",
    website: "www.maxi.rs",
    contact: "Srđan Radosavljević",
    vatNumber: "100232066",
    companyNumber: "17580167",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11070",
    note: "Vlasnik Maxi supermarketa, vodeći maloprodajni lanac.",
    createdAt: pastDate(350),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Hemofarm a.d.",
    industry: "Healthcare",
    address: "Beogradski put bb",
    email: "office@hemofarm.com",
    phone: "+381 13 803 100",
    website: "www.hemofarm.com",
    contact: "Ronald Seeliger",
    vatNumber: "100246269",
    companyNumber: "08000100",
    city: "Vršac",
    country: "Serbia",
    countryCode: "RS",
    zip: "26300",
    note: "Vodeća farmaceutska kompanija u Srbiji, deo STADA grupe.",
    createdAt: pastDate(380),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Telenor d.o.o. Beograd",
    industry: "Telecommunications",
    address: "Omladinskih brigada 90",
    email: "info@telenor.rs",
    phone: "+381 63 9000",
    website: "www.telenor.rs",
    contact: "Milica Stojanović",
    vatNumber: "104318304",
    companyNumber: "20147229",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11070",
    note: "Mobilni operater u vlasništvu PPF grupe.",
    createdAt: pastDate(320),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "FCA Srbija d.o.o.",
    industry: "Automotive",
    address: "Kosovska 4",
    email: "info@fcasrbija.rs",
    phone: "+381 34 335 200",
    website: "www.fcasrbija.rs",
    contact: "Silvia Vernetti",
    vatNumber: "106013267",
    companyNumber: "20575417",
    city: "Kragujevac",
    country: "Serbia",
    countryCode: "RS",
    zip: "34000",
    note: "Fabrika automobila FIAT u Kragujevcu.",
    createdAt: pastDate(340),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Apatinska pivara d.o.o.",
    industry: "Food & Beverage",
    address: "Trg Oslobođenja 5",
    email: "info@jfrb.rs",
    phone: "+381 25 772 022",
    website: "www.jfrb.rs",
    contact: "Dragan Vukić",
    vatNumber: "100002020",
    companyNumber: "08000022",
    city: "Apatin",
    country: "Serbia",
    countryCode: "RS",
    zip: "25260",
    note: "Proizvođač Jelen piva, deo Molson Coors grupe.",
    createdAt: pastDate(290),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Metalac a.d.",
    industry: "Manufacturing",
    address: "Kneza Aleksandra 212",
    email: "office@metalac.com",
    phone: "+381 32 381 100",
    website: "www.metalac.com",
    contact: "Dragan Nikolić",
    vatNumber: "100102201",
    companyNumber: "07185901",
    city: "Gornji Milanovac",
    country: "Serbia",
    countryCode: "RS",
    zip: "32300",
    note: "Proizvođač metalnog posuđa i kućnih aparata.",
    createdAt: pastDate(310),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Imlek a.d.",
    industry: "Food & Beverage",
    address: "Industrijsko naselje bb",
    email: "info@imlek.rs",
    phone: "+381 11 307 5555",
    website: "www.imlek.rs",
    contact: "Nenad Živković",
    vatNumber: "100022987",
    companyNumber: "07034849",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11213",
    note: "Najveći proizvođač mleka i mlečnih proizvoda u Srbiji.",
    createdAt: pastDate(280),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "MK Group d.o.o.",
    industry: "Agriculture",
    address: "Bulevar Mihajla Pupina 115E",
    email: "office@mkgroup.rs",
    phone: "+381 11 201 0800",
    website: "www.mkgroup.rs",
    contact: "Miodrag Kostić",
    vatNumber: "101653291",
    companyNumber: "17520784",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11070",
    note: "Vodeća agro-industrijska grupacija u regionu.",
    createdAt: pastDate(260),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Henkel Srbija d.o.o.",
    industry: "Manufacturing",
    address: "Bulevar Oslobođenja 383",
    email: "info@henkel.rs",
    phone: "+381 11 209 0800",
    website: "www.henkel.rs",
    contact: "Thomas Holzer",
    vatNumber: "100000054",
    companyNumber: "06969267",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11000",
    note: "Proizvođač deterdženata i kozmetike.",
    createdAt: pastDate(300),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Komercijalna banka a.d.",
    industry: "Finance",
    address: "Svetog Save 14",
    email: "info@kombank.com",
    phone: "+381 11 308 0100",
    website: "www.kombank.com",
    contact: "Vladimir Čupić",
    vatNumber: "100002534",
    companyNumber: "07737971",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11000",
    note: "Druga najveća banka u Srbiji po aktivi.",
    createdAt: pastDate(380),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Nelt d.o.o.",
    industry: "Logistics",
    address: "Maršala Birjuzova 3-5",
    email: "info@nelt.com",
    phone: "+381 11 206 0300",
    website: "www.nelt.com",
    contact: "Siniša Mitrović",
    vatNumber: "100082645",
    companyNumber: "07434804",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11000",
    note: "Vodeća distribucijska kompanija za FMCG proizvode.",
    createdAt: pastDate(270),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Tarkett d.o.o.",
    industry: "Manufacturing",
    address: "Industrijska zona bb",
    email: "info@tarkett.rs",
    phone: "+381 22 312 700",
    website: "www.tarkett.rs",
    contact: "Fabrice Barthélemy",
    vatNumber: "101102356",
    companyNumber: "08049459",
    city: "Bačka Palanka",
    country: "Serbia",
    countryCode: "RS",
    zip: "21400",
    note: "Proizvođač podnih obloga, deo Tarkett Group.",
    createdAt: pastDate(340),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Eurobank Direktna a.d.",
    industry: "Finance",
    address: "Vuka Karadžića 10",
    email: "info@eurobank.rs",
    phone: "+381 11 206 5000",
    website: "www.eurobank.rs",
    contact: "Slavica Pavlović",
    vatNumber: "100002569",
    companyNumber: "07738552",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11000",
    note: "Banka u vlasništvu grčke Eurobank grupe.",
    createdAt: pastDate(330),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Bambi a.d.",
    industry: "Food & Beverage",
    address: "Đure Jakšića 7",
    email: "info@bambi.rs",
    phone: "+381 26 411 133",
    website: "www.bambi.rs",
    contact: "Miroslav Perić",
    vatNumber: "100020147",
    companyNumber: "07182155",
    city: "Požarevac",
    country: "Serbia",
    countryCode: "RS",
    zip: "12000",
    note: "Proizvođač konditorskih proizvoda, vlasnik brenda Plazma.",
    createdAt: pastDate(350),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Tigar Tyres d.o.o.",
    industry: "Automotive",
    address: "Nikole Pašića 213",
    email: "info@tigar.rs",
    phone: "+381 10 302 000",
    website: "www.tigar.rs",
    contact: "Milan Živković",
    vatNumber: "100020003",
    companyNumber: "07133669",
    city: "Pirot",
    country: "Serbia",
    countryCode: "RS",
    zip: "18300",
    note: "Proizvođač pneumatika, deo Michelin grupe.",
    createdAt: pastDate(360),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Informatika a.d.",
    industry: "Technology",
    address: "Vojvode Stepe 88",
    email: "office@informatika.com",
    phone: "+381 11 397 2600",
    website: "www.informatika.com",
    contact: "Zoran Marinković",
    vatNumber: "100002445",
    companyNumber: "07727941",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11000",
    note: "IT kompanija specijalizovana za softverska rešenja.",
    createdAt: pastDate(250),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Lilly Drogerie d.o.o.",
    industry: "Retail",
    address: "Bulevar Zorana Đinđića 64a",
    email: "info@lilly.rs",
    phone: "+381 11 715 5555",
    website: "www.lilly.rs",
    contact: "Duško Knežević",
    vatNumber: "103188082",
    companyNumber: "17610023",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11070",
    note: "Lanac drogerija sa preko 200 prodavnica u Srbiji.",
    createdAt: pastDate(230),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Victoria Group a.d.",
    industry: "Agriculture",
    address: "Vojvode Stepe 12",
    email: "office@victoriagroup.rs",
    phone: "+381 11 355 6000",
    website: "www.victoriagroup.rs",
    contact: "Zoran Mitrović",
    vatNumber: "104028745",
    companyNumber: "20083310",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11000",
    note: "Poljoprivredno-prehrambena grupacija, proizvođač ulja i brašna.",
    createdAt: pastDate(300),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Gomex d.o.o.",
    industry: "Retail",
    address: "Sremska 1",
    email: "info@gomex.rs",
    phone: "+381 23 525 555",
    website: "www.gomex.rs",
    contact: "Radivoje Petrović",
    vatNumber: "100051689",
    companyNumber: "08165882",
    city: "Zrenjanin",
    country: "Serbia",
    countryCode: "RS",
    zip: "23000",
    note: "Regionalni lanac supermarketa u Vojvodini.",
    createdAt: pastDate(220),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Philip Morris Operations a.d.",
    industry: "Manufacturing",
    address: "Bulevar Nikole Tesle 5a",
    email: "pmserbia@pmi.com",
    phone: "+381 18 530 100",
    website: "www.pmi.com",
    contact: "Stefan Lazić",
    vatNumber: "100019987",
    companyNumber: "07142366",
    city: "Niš",
    country: "Serbia",
    countryCode: "RS",
    zip: "18000",
    note: "Fabrika duvanskih proizvoda, deo Philip Morris International.",
    createdAt: pastDate(370),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Soko Štark d.o.o.",
    industry: "Food & Beverage",
    address: "Kumodraška 249",
    email: "info@stark.rs",
    phone: "+381 11 309 1100",
    website: "www.stark.rs",
    contact: "Nebojša Simić",
    vatNumber: "100005577",
    companyNumber: "07032056",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11000",
    note: "Proizvođač čokolade i konditorskih proizvoda.",
    createdAt: pastDate(340),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Asseco SEE d.o.o.",
    industry: "Technology",
    address: "Bulevar Milutina Milankovića 19a",
    email: "office@asseco-see.rs",
    phone: "+381 11 209 7800",
    website: "www.asseco-see.com",
    contact: "Piotr Jeleński",
    vatNumber: "103541345",
    companyNumber: "20167823",
    city: "Belgrade",
    country: "Serbia",
    countryCode: "RS",
    zip: "11070",
    note: "IT kompanija specijalizovana za bankarske sisteme i ERP rešenja.",
    createdAt: pastDate(240),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Nectar d.o.o.",
    industry: "Food & Beverage",
    address: "Železnička bb",
    email: "office@nectar.rs",
    phone: "+381 22 543 530",
    website: "www.nectar.rs",
    contact: "Vladimir Panić",
    vatNumber: "101500199",
    companyNumber: "08595551",
    city: "Bačka Palanka",
    country: "Serbia",
    countryCode: "RS",
    zip: "21400",
    note: "Proizvođač sokova i voćnih prerađevina.",
    createdAt: pastDate(280),
    updatedAt: now(),
  },
];

// ============================================
// 25 Global Companies - Real Data
// ============================================

export const GLOBAL_COMPANIES: Company[] = [
  {
    id: generateUUID(),
    name: "Microsoft Corporation",
    industry: "Technology",
    address: "One Microsoft Way",
    email: "support@microsoft.com",
    phone: "+1 425 882 8080",
    website: "www.microsoft.com",
    contact: "Satya Nadella",
    vatNumber: "US91-0718661",
    companyNumber: "91-0718661",
    city: "Redmond, WA",
    country: "United States",
    countryCode: "US",
    zip: "98052",
    note: "Global technology leader in software, cloud, and hardware.",
    createdAt: pastDate(500),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Apple Inc.",
    industry: "Technology",
    address: "One Apple Park Way",
    email: "contact@apple.com",
    phone: "+1 408 996 1010",
    website: "www.apple.com",
    contact: "Tim Cook",
    vatNumber: "US94-2404110",
    companyNumber: "94-2404110",
    city: "Cupertino, CA",
    country: "United States",
    countryCode: "US",
    zip: "95014",
    note: "Consumer electronics, software, and online services.",
    createdAt: pastDate(520),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Amazon.com Inc.",
    industry: "E-commerce",
    address: "410 Terry Avenue North",
    email: "contact@amazon.com",
    phone: "+1 206 266 1000",
    website: "www.amazon.com",
    contact: "Andy Jassy",
    vatNumber: "US91-1646860",
    companyNumber: "91-1646860",
    city: "Seattle, WA",
    country: "United States",
    countryCode: "US",
    zip: "98109",
    note: "World's largest e-commerce and cloud computing company.",
    createdAt: pastDate(480),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Volkswagen AG",
    industry: "Automotive",
    address: "Berliner Ring 2",
    email: "info@volkswagen.de",
    phone: "+49 5361 90",
    website: "www.volkswagen.com",
    contact: "Oliver Blume",
    vatNumber: "DE115235681",
    companyNumber: "HRB100484",
    city: "Wolfsburg",
    country: "Germany",
    countryCode: "DE",
    zip: "38440",
    note: "World's second-largest automaker by sales.",
    createdAt: pastDate(550),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Samsung Electronics Co., Ltd.",
    industry: "Technology",
    address: "129 Samsung-ro, Yeongtong-gu",
    email: "contact@samsung.com",
    phone: "+82 2 2255 0114",
    website: "www.samsung.com",
    contact: "Jong-Hee Han",
    vatNumber: "KR129-81-00998",
    companyNumber: "129-81-00998",
    city: "Suwon",
    country: "South Korea",
    countryCode: "KR",
    zip: "16677",
    note: "Global leader in memory chips, smartphones, and displays.",
    createdAt: pastDate(510),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Toyota Motor Corporation",
    industry: "Automotive",
    address: "1 Toyota-cho",
    email: "global@toyota.co.jp",
    phone: "+81 565 28 2121",
    website: "www.toyota.com",
    contact: "Koji Sato",
    vatNumber: "JP2180001080407",
    companyNumber: "2180001080407",
    city: "Toyota City",
    country: "Japan",
    countryCode: "JP",
    zip: "471-8571",
    note: "World's largest automaker by production volume.",
    createdAt: pastDate(560),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Nestlé S.A.",
    industry: "Food & Beverage",
    address: "Avenue Nestlé 55",
    email: "info@nestle.com",
    phone: "+41 21 924 2111",
    website: "www.nestle.com",
    contact: "Mark Schneider",
    vatNumber: "CHE-115.857.826",
    companyNumber: "CH-660.0.008.545-0",
    city: "Vevey",
    country: "Switzerland",
    countryCode: "CH",
    zip: "1800",
    note: "World's largest food and beverage company.",
    createdAt: pastDate(580),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "LVMH Moët Hennessy Louis Vuitton",
    industry: "Luxury Goods",
    address: "22 Avenue Montaigne",
    email: "contact@lvmh.com",
    phone: "+33 1 44 13 22 22",
    website: "www.lvmh.com",
    contact: "Bernard Arnault",
    vatNumber: "FR77775670417",
    companyNumber: "775670417",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    zip: "75008",
    note: "World's largest luxury goods conglomerate.",
    createdAt: pastDate(540),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Shell plc",
    industry: "Energy",
    address: "Shell Centre, York Road",
    email: "contactshell@shell.com",
    phone: "+44 20 7934 1234",
    website: "www.shell.com",
    contact: "Wael Sawan",
    vatNumber: "GB574507843",
    companyNumber: "04366849",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    zip: "SE1 7NA",
    note: "One of the world's largest oil and gas companies.",
    createdAt: pastDate(570),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Siemens AG",
    industry: "Manufacturing",
    address: "Werner-von-Siemens-Straße 1",
    email: "contact@siemens.com",
    phone: "+49 89 636 00",
    website: "www.siemens.com",
    contact: "Roland Busch",
    vatNumber: "DE129274202",
    companyNumber: "HRB6684",
    city: "Munich",
    country: "Germany",
    countryCode: "DE",
    zip: "80333",
    note: "Global technology company in automation and digitalization.",
    createdAt: pastDate(530),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "HSBC Holdings plc",
    industry: "Finance",
    address: "8 Canada Square",
    email: "customerservice@hsbc.com",
    phone: "+44 20 7991 8888",
    website: "www.hsbc.com",
    contact: "Noel Quinn",
    vatNumber: "GB629804121",
    companyNumber: "00617987",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    zip: "E14 5HQ",
    note: "One of the world's largest banking and financial services.",
    createdAt: pastDate(590),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Unilever PLC",
    industry: "Consumer Goods",
    address: "100 Victoria Embankment",
    email: "info@unilever.com",
    phone: "+44 20 7822 5252",
    website: "www.unilever.com",
    contact: "Hein Schumacher",
    vatNumber: "GB576682991",
    companyNumber: "00041424",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    zip: "EC4Y 0DY",
    note: "Global consumer goods company with food, beauty, and home care.",
    createdAt: pastDate(550),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Alibaba Group Holding Limited",
    industry: "E-commerce",
    address: "969 West Wen Yi Road",
    email: "alibabagroup@alibaba-inc.com",
    phone: "+86 571 8502 2088",
    website: "www.alibaba.com",
    contact: "Eddie Wu",
    vatNumber: "91330000799655058R",
    companyNumber: "AYT1688",
    city: "Hangzhou",
    country: "China",
    countryCode: "CN",
    zip: "311121",
    note: "China's largest e-commerce company.",
    createdAt: pastDate(460),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Novartis AG",
    industry: "Healthcare",
    address: "Lichtstrasse 35",
    email: "contact@novartis.com",
    phone: "+41 61 324 1111",
    website: "www.novartis.com",
    contact: "Vas Narasimhan",
    vatNumber: "CHE-108.801.656",
    companyNumber: "CH-270.3.001.177-9",
    city: "Basel",
    country: "Switzerland",
    countryCode: "CH",
    zip: "4056",
    note: "Global healthcare company focusing on pharmaceuticals.",
    createdAt: pastDate(500),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Johnson & Johnson",
    industry: "Healthcare",
    address: "One Johnson & Johnson Plaza",
    email: "jnj@jnj.com",
    phone: "+1 732 524 0400",
    website: "www.jnj.com",
    contact: "Joaquin Duato",
    vatNumber: "US22-1024240",
    companyNumber: "22-1024240",
    city: "New Brunswick, NJ",
    country: "United States",
    countryCode: "US",
    zip: "08933",
    note: "Multinational pharmaceutical and medical devices company.",
    createdAt: pastDate(580),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "BMW AG",
    industry: "Automotive",
    address: "Petuelring 130",
    email: "info@bmw.de",
    phone: "+49 89 382 0",
    website: "www.bmw.com",
    contact: "Oliver Zipse",
    vatNumber: "DE129273398",
    companyNumber: "HRB42243",
    city: "Munich",
    country: "Germany",
    countryCode: "DE",
    zip: "80788",
    note: "German luxury vehicle manufacturer.",
    createdAt: pastDate(540),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "L'Oréal S.A.",
    industry: "Consumer Goods",
    address: "41 Rue Martre",
    email: "contact@loreal.com",
    phone: "+33 1 47 56 70 00",
    website: "www.loreal.com",
    contact: "Nicolas Hieronimus",
    vatNumber: "FR06632012100",
    companyNumber: "632012100",
    city: "Clichy",
    country: "France",
    countryCode: "FR",
    zip: "92110",
    note: "World's largest cosmetics company.",
    createdAt: pastDate(560),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Intel Corporation",
    industry: "Technology",
    address: "2200 Mission College Boulevard",
    email: "intel@intel.com",
    phone: "+1 408 765 8080",
    website: "www.intel.com",
    contact: "Pat Gelsinger",
    vatNumber: "US94-1672743",
    companyNumber: "94-1672743",
    city: "Santa Clara, CA",
    country: "United States",
    countryCode: "US",
    zip: "95054",
    note: "World's largest semiconductor chip manufacturer by revenue.",
    createdAt: pastDate(530),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Sony Group Corporation",
    industry: "Technology",
    address: "1-7-1 Konan, Minato-ku",
    email: "info@sony.com",
    phone: "+81 3 6748 2111",
    website: "www.sony.com",
    contact: "Kenichiro Yoshida",
    vatNumber: "JP2010401017275",
    companyNumber: "2010401017275",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    zip: "108-0075",
    note: "Global conglomerate in electronics, gaming, and entertainment.",
    createdAt: pastDate(570),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "PepsiCo Inc.",
    industry: "Food & Beverage",
    address: "700 Anderson Hill Road",
    email: "consumer@pepsico.com",
    phone: "+1 914 253 2000",
    website: "www.pepsico.com",
    contact: "Ramon Laguarta",
    vatNumber: "US13-1584302",
    companyNumber: "13-1584302",
    city: "Purchase, NY",
    country: "United States",
    countryCode: "US",
    zip: "10577",
    note: "Multinational food, snack, and beverage corporation.",
    createdAt: pastDate(550),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "SAP SE",
    industry: "Technology",
    address: "Dietmar-Hopp-Allee 16",
    email: "info@sap.com",
    phone: "+49 6227 747474",
    website: "www.sap.com",
    contact: "Christian Klein",
    vatNumber: "DE143632856",
    companyNumber: "HRB330017",
    city: "Walldorf",
    country: "Germany",
    countryCode: "DE",
    zip: "69190",
    note: "World's leading enterprise application software company.",
    createdAt: pastDate(490),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "AstraZeneca PLC",
    industry: "Healthcare",
    address: "1 Francis Crick Avenue",
    email: "company@astrazeneca.com",
    phone: "+44 20 3749 5000",
    website: "www.astrazeneca.com",
    contact: "Pascal Soriot",
    vatNumber: "GB648975430",
    companyNumber: "02723534",
    city: "Cambridge",
    country: "United Kingdom",
    countryCode: "GB",
    zip: "CB2 0AA",
    note: "British-Swedish pharmaceutical and biotechnology company.",
    createdAt: pastDate(510),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Cisco Systems Inc.",
    industry: "Technology",
    address: "170 West Tasman Drive",
    email: "info@cisco.com",
    phone: "+1 408 526 4000",
    website: "www.cisco.com",
    contact: "Chuck Robbins",
    vatNumber: "US77-0059951",
    companyNumber: "77-0059951",
    city: "San Jose, CA",
    country: "United States",
    countryCode: "US",
    zip: "95134",
    note: "Global leader in networking hardware and telecommunications.",
    createdAt: pastDate(520),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Nike Inc.",
    industry: "Consumer Goods",
    address: "One Bowerman Drive",
    email: "nikebusiness@nike.com",
    phone: "+1 503 671 6453",
    website: "www.nike.com",
    contact: "John Donahoe",
    vatNumber: "US93-0584541",
    companyNumber: "93-0584541",
    city: "Beaverton, OR",
    country: "United States",
    countryCode: "US",
    zip: "97005",
    note: "World's largest supplier of athletic shoes and apparel.",
    createdAt: pastDate(540),
    updatedAt: now(),
  },
  {
    id: generateUUID(),
    name: "Roche Holding AG",
    industry: "Healthcare",
    address: "Grenzacherstrasse 124",
    email: "info@roche.com",
    phone: "+41 61 688 1111",
    website: "www.roche.com",
    contact: "Thomas Schinecker",
    vatNumber: "CHE-105.879.765",
    companyNumber: "CH-270.3.000.243-6",
    city: "Basel",
    country: "Switzerland",
    countryCode: "CH",
    zip: "4070",
    note: "World's largest biotech company and leading diagnostics provider.",
    createdAt: pastDate(570),
    updatedAt: now(),
  },
];

// ============================================
// Seed Function for Companies
// ============================================

async function seedCompaniesData(companies: Company[]): Promise<string[]> {
  console.log("📦 Seeding companies...");
  const ids: string[] = [];

  for (const company of companies) {
    try {
      const existing = await companyQueries.findByName(company.name);
      if (existing) {
        // Update existing company with all fields
        console.log(`  🔄 Updating company: ${company.name}`);
        await companyQueries.update(existing.id, company);
        ids.push(existing.id);
      } else {
        const created = await companyQueries.createWithId(company);
        console.log(`  ✅ Created company: ${created.name} (${company.city}, ${company.countryCode})`);
        ids.push(created.id);
      }
    } catch (error) {
      console.error(`  ❌ Failed to create/update company ${company.name}:`, error);
    }
  }

  return ids;
}

export async function seedSerbianAndGlobalCompanies(): Promise<void> {
  console.log("\n🌱 Starting seed for Serbian and Global companies...\n");

  try {
    console.log("\n🇷🇸 SERBIAN COMPANIES (25):\n");
    console.log("═".repeat(50));
    const serbianIds = await seedCompaniesData(SERBIAN_COMPANIES);
    console.log(`\n  📊 Serbian companies seeded: ${serbianIds.length}\n`);

    console.log("\n🌍 GLOBAL COMPANIES (25):\n");
    console.log("═".repeat(50));
    const globalIds = await seedCompaniesData(GLOBAL_COMPANIES);
    console.log(`\n  📊 Global companies seeded: ${globalIds.length}\n`);

    // Summary
    const companyCount = await db`SELECT COUNT(*) FROM companies`;
    console.log("\n📊 Final Summary:");
    console.log("═".repeat(50));
    console.log(`   Total Serbian companies added: ${serbianIds.length}`);
    console.log(`   Total Global companies added: ${globalIds.length}`);
    console.log(`   Total companies in database:  ${parseInt(companyCount[0].count as string, 10)}`);
    console.log("═".repeat(50));
    console.log("\n✅ Company seeding completed!\n");
  } catch (error) {
    console.error("\n❌ Seed failed:", error);
    throw error;
  }
}

// CLI runner
if (import.meta.main) {
  try {
    await seedSerbianAndGlobalCompanies();
    await db.end();
    process.exit(0);
  } catch (error) {
    console.error("Seed error:", error);
    await db.end();
    process.exit(1);
  }
}
